version: "3.8"

services:
  nginx_1:
    image: nginx
    ports:
      - 8088:80
    links:
      - fpm_api
    volumes:
      - ./app/api:/var/www/webmoder/api
      - ./docker/nginx/api.conf:/etc/nginx/conf.d/default.conf

  nginx_2:
    image: nginx
    ports:
      - 8089:80
    links:
      - fpm_fake_sms
    volumes:
      - ./app/fake_sms:/var/www/webmoder/fake_sms
      - ./docker/nginx/fake_sms.conf:/etc/nginx/conf.d/default.conf

  fpm_api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    volumes:
      - ./app/api:/var/www/webmoder/api
    links:
      - redis

  fpm_fake_sms:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/fpm.Dockerfile
    volumes:
      - ./app/fake_sms:/var/www/webmoder/fake_sms

  php_cli:
    env_file:
      - .env
    build:
      context: .
      dockerfile: docker/cli.Dockerfile
    volumes:
      - ./app/fake_sms:/var/www/webmoder/fake_sms
    command: php /var/www/webmoder/fake_sms/listener.php
    links:
      - redis

  redis:
    image: redis
    restart: always
    volumes:
      - ./storage/redis/data:/data
    ports:
      - 6379:6379